### PR TITLE
OwnCloud blueprint

### PR DESCRIPTION
**Pull request by magonzalez192**

### CODE REVIEW

**Comment by akarasulu** [comment]
Hi there, it seems someone already did own cloud but did not update this document. Can you pick something else?

**Comment by efeefe** [comment]
Hi @magonzalez192 thanks for your interest. Let us know if you need any support in understanding how Blueprints work. I take you have already read our [wiki page](https://github.com/subutai-blueprints/hackathon/wiki/Writing-Subutai-Blueprints) about it?

**Comment by magonzalez192** [comment]
Hi, @akarasulu : 
I didn't say anyone taking it, or pending pull request. If this is a problem, tell me and I could choose another one.

Hi, @efeefe :
Yeah, I read it already, and other blueprints as example.

**Comment by akarasulu** [comment]
Hey @magonzalez192 seems I'm confused with all the fooclouds out there. Seems it is free let me fix this. Next time we will make sure this confusion does not happen again. @efeefe can you sync up with that is actually done and not done to update this matrix? Thanks!

**Pull request merged**
